spring:
  ####整合数据库层
  datasource:
    emp:
      driver-class-name: com.mysql.cj.jdbc.Driver
      name: master
      url: jdbc:mysql://127.0.0.1:3306/emp?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
      username: root
      password: 1
      # Hikari will use the above plus the following to setup connection pooling
      type: com.alibaba.druid.pool.DruidDataSource
    #hy2:
    #  driver-class-name: com.mysql.cj.jdbc.Driver
    #  name: hy2
    #  jdbc-url: jdbc:mysql://127.0.0.1:3306/trs_hycloud_iip?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    #  jdbc-url: jdbc:mysql://10.6.1.237:3306/wos?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    #  username: root
    #  password: 1
    druid:
      # 初始连接数
      initialSize: 5
      # 最小连接池数量
      minIdle: 10
      # 最大连接池数量
      maxActive: 20
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      # 配置一个连接在池中最大生存的时间，单位是毫秒
      maxEvictableIdleTimeMillis: 900000
      # 配置检测连接是否有效
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      webStatFilter:  # http://localhost/trsapi/druid/login.html DruidFilterConfiguration
        enabled: true
      statViewServlet:
        enabled: true
        # 设置白名单，不填则允许所有访问
        allow:
        url-pattern: /druid/*
        # 控制台管理用户名和密码
        login-username: easy
        login-password: 1
      filter:
        stat:
          enabled: true
          # 慢SQL记录
          log-slow-sql: true
          slow-sql-millis: 20000
          merge-sql: true
        wall:
          config:
            multi-statement-allow: true